ALTER TABLE inquiries
ADD COLUMN IF NOT EXISTS gender VARCHAR(10),
ADD COLUMN IF NOT EXISTS matric_marks INTEGER,
ADD COLUMN IF NOT EXISTS out_of_marks INTEGER,
ADD COLUMN IF NOT EXISTS intermediate_stream VARCHAR(50);
